// <auto-generated />
using System;
using Listrr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Listrr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210121180111_0")]
    partial class _0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Listrr.Data.CountryCode", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Name", "Code");

                    b.HasIndex("Code");

                    b.ToTable("CountryCodes");
                });

            modelBuilder.Entity("Listrr.Data.IMDb.IMDbRating", b =>
                {
                    b.Property<string>("IMDbId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("IMDbId");

                    b.HasIndex("IMDbId")
                        .IsUnique();

                    b.ToTable("ImDbRatings");
                });

            modelBuilder.Entity("Listrr.Data.LanguageCode", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Name", "Code");

                    b.HasIndex("Code");

                    b.ToTable("LanguageCodes");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktList", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<string>("ExclusionFilter_Certifications_Movie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Certifications_Show")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Countries")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Genres")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Keywords")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Languages")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Networks")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExclusionFilter_Translations")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Certifications_Movie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Certifications_Show")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Countries")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Genres")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Languages")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Networks")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Ratings_IMDb")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Ratings_Trakt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Runtimes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Translations")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Filter_Years")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ItemList")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Items")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastProcessed")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OwnerId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("Process")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Query")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ScanState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<bool>("SearchByAlias")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByBiography")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByDescription")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByName")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByOverview")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByPeople")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByTagline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByTitle")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchByTranslations")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("TraktLists");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktMovieCertification", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Slug");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TraktMovieCertifications");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktMovieGenre", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Slug");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TraktMovieGenres");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktShowCertification", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Slug");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TraktShowCertifications");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktShowGenre", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Slug");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TraktShowGenres");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktShowNetwork", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TraktShowNetworks");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktShowStatus", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TraktShowStatuses");
                });

            modelBuilder.Entity("Listrr.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Listrr.Data.Trakt.TraktList", b =>
                {
                    b.HasOne("Listrr.Data.User", "Owner")
                        .WithMany("TraktLists")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Listrr.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Listrr.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listrr.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Listrr.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Listrr.Data.User", b =>
                {
                    b.Navigation("TraktLists");
                });
#pragma warning restore 612, 618
        }
    }
}
